### ISSUE TITLE
Allow folder location to be current directory and not root

### ISSUE THREAD

**Issue by AnthonyPoschen** [Kicamon/ranger.nvim#2]
would be nice if a config can be set to use the current directory of the active file rather than the root.

**Comment by Kicamon** [comment]
you can try set `vim.opt.autochdir = true`

**Comment by AnthonyPoschen** [comment]
yeah autochdir does the trick. would add value for others maybe being a note in the readme.
coming from francoiscabrol/ranger.vim it just worked.

**Comment by AnthonyPoschen** [comment]
gonna re open because i noticed when using this method, it culls my fuzzy file search list as i go deep inside a folder tree.

essentially i like to fuzzy find files within the tree and open by name if i know what i am looking for then lean on ranger to find nearby files or handle directory management, moving and creating files / folders.

**Comment by Kicamon** [comment]
ok, i understand

**Comment by Kicamon** [comment]
solved

**Comment by AnthonyPoschen** [comment]
yeah been using it for about an hour flawlessly. thank you very much.
all my little issues now fully resolved can move onto this full time <3
