### ISSUE TITLE
Leaving floating window breaks functionality.

### ISSUE THREAD

**Issue by AnthonyPoschen** [Kicamon/ranger.nvim#3]
When leaving the floating window by accident via keybinds when returning functionality stops work and when closing and reopening it stops working requiring a nvim close and reopen.

**Comment by Kicamon** [comment]
show me with gif please

**Comment by AnthonyPoschen** [comment]
disregard, cleaned my install completely to be sure, as i noticed i downloaded this project origionally on the day of release, after a full clean its working as expected.
